pipeline {
    agent any
    stages {
        stage("firstStage"){
            steps {
                sh "echo 'Hello World1'"
                sh "apt-get install pip3"
                sh "python --version"
            }
        }
        stage("secondStage"){
            steps {
                sh "echo 'hello world 2'"
            }
        }
    }
}
