pipeline {
    agent any
    stages {
        stage("firstStage"){
            steps {
                sh "echo 'Hello World1'"
                sh "python3 --version"
                sh "echo 'print(\"Hello World inside python file\")' >> myfile.py"
                sh "python3 myfile.py"
            }
        }
        stage("secondStage"){
            steps {
                sh "echo 'hello world from main-branch'"
            }
        }
    }
}
